/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ardagurkan
 */
import javax.swing.*;
public class Type2MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Type2MainFrame
     */
    private DB db;
    private User user;
    
    public Type2MainFrame(DB db, User user) {
        initComponents();
        this.db = db;
        this.user = user;

        setTitle("MyLibrary - User Panel (Type 2)");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
        initComponents();
        db.notifyUpcomingWishlistBooks(user.getUserId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        FavoriteBooks = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SeeCover = new javax.swing.JToggleButton();
        FavoriteAuthors = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MyLibrary");

        jButton1.setText("Search Author");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        FavoriteBooks.setText("Favorite Books");
        FavoriteBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoriteBooksActionPerformed(evt);
            }
        });

        jButton2.setText("UnreadBooks");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        SeeCover.setText("SeeCover");
        SeeCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeCoverActionPerformed(evt);
            }
        });

        FavoriteAuthors.setText("Favorite Authors");
        FavoriteAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoriteAuthorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(FavoriteBooks))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SeeCover)
                        .addGap(68, 68, 68)
                        .addComponent(FavoriteAuthors)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(164, 164, 164))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(FavoriteBooks))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeeCover)
                    .addComponent(FavoriteAuthors))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new SearchAuthorFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FavoriteBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoriteBooksActionPerformed
        // TODO add your handling code here:
        new FavoriteBookFrame(user);
    }//GEN-LAST:event_FavoriteBooksActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new UnreadBooksFrame(user.getUserId());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SeeCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeCoverActionPerformed
        // TODO add your handling code here:
        new CoverFrame();
    }//GEN-LAST:event_SeeCoverActionPerformed

    private void FavoriteAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoriteAuthorsActionPerformed
        // TODO add your handling code here:
        new FavoriteAuthorsFrame(user.getUserId());
    }//GEN-LAST:event_FavoriteAuthorsActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FavoriteAuthors;
    private javax.swing.JButton FavoriteBooks;
    private javax.swing.JToggleButton SeeCover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
