/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ardagurkan
 */

import javax.swing.*;

public class Type1MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Type1MainFrame
     */
    private DB db;
    private User user;
    
    public Type1MainFrame(DB db, User user) {
        initComponents();
        this.db = db;
        this.user = user;

        setTitle("MyLibrary - Admin Panel");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        initComponents();
        db.notifyUpcomingWishlistBooks(user.getUserId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddBook = new javax.swing.JButton();
        DeleteBook = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SearchAuthorName = new javax.swing.JButton();
        FavoriteBooks = new javax.swing.JButton();
        FavoriteAuthors = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        UnreadBooks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Admin's Page");

        AddBook.setText("Add Book");
        AddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookActionPerformed(evt);
            }
        });

        DeleteBook.setText("Delete Book");
        DeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBookActionPerformed(evt);
            }
        });

        jButton1.setText("Display Book Info/Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SearchAuthorName.setText("Search Author Name");
        SearchAuthorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchAuthorNameActionPerformed(evt);
            }
        });

        FavoriteBooks.setText("Favorite Books");
        FavoriteBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoriteBooksActionPerformed(evt);
            }
        });

        FavoriteAuthors.setText("Favorite Authors");
        FavoriteAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoriteAuthorsActionPerformed(evt);
            }
        });

        jButton5.setText("Book Cover");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        UnreadBooks.setText("Unread Books");
        UnreadBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnreadBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AddBook)
                .addGap(40, 40, 40)
                .addComponent(DeleteBook)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UnreadBooks)
                .addGap(62, 62, 62)
                .addComponent(jButton5)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addComponent(SearchAuthorName)
                .addGap(52, 52, 52)
                .addComponent(FavoriteBooks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(FavoriteAuthors))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBook)
                    .addComponent(DeleteBook)
                    .addComponent(jButton1))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchAuthorName)
                    .addComponent(FavoriteBooks)
                    .addComponent(FavoriteAuthors))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnreadBooks)
                    .addComponent(jButton5))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookActionPerformed
        // TODO add your handling code here:
        new AddBookFrame();
       
    }//GEN-LAST:event_AddBookActionPerformed

    private void DeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookActionPerformed
        // TODO add your handling code here:
        new DeleteBookFrame();
    }//GEN-LAST:event_DeleteBookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new BookInfoFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchAuthorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchAuthorNameActionPerformed
        // TODO add your handling code here:
        new SearchAuthorFrame();
    }//GEN-LAST:event_SearchAuthorNameActionPerformed

    private void FavoriteBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoriteBooksActionPerformed
        // TODO add your handling code here:
        new FavoriteBookFrame(user);
    }//GEN-LAST:event_FavoriteBooksActionPerformed

    private void FavoriteAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoriteAuthorsActionPerformed
        // TODO add your handling code here:
        new FavoriteAuthorsFrame(user.getUserId());
    }//GEN-LAST:event_FavoriteAuthorsActionPerformed

    private void UnreadBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnreadBooksActionPerformed
        // TODO add your handling code here:
        new UnreadBooksFrame(user.getUserId());
    }//GEN-LAST:event_UnreadBooksActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new CoverFrame();
    }//GEN-LAST:event_jButton5ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBook;
    private javax.swing.JButton DeleteBook;
    private javax.swing.JButton FavoriteAuthors;
    private javax.swing.JButton FavoriteBooks;
    private javax.swing.JButton SearchAuthorName;
    private javax.swing.JButton UnreadBooks;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
